config/routes.rb
Rails.application.routes.draw do

  get 'help/getting_started'
  get 'help/webapp_setup'

  authenticated :user do
    root :to => "nodes#index", as: :authenticated_root
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :nodes do
  	member do
  		post 'import'
      post 'export'
  	end
  end

  post 'input/read'

  get 'stats/:node_id/dashboard' => 'stats#dashboard', as: :dashboard_stats
  get 'stats/:node_id/time_series_data' => 'stats#time_series_data', as: :time_series_data_stats
  get 'stats/:node_id/yearly_data' => 'stats#yearly_data', as: :yearly_data_stats
  # get 'stats/:node_id/monthly' => 'stats#chart', as: :monthly_stats
  get 'stats/:node_id/monthly_data' => 'stats#monthly_data', as: :monthly_data_stats
  # get 'stats/:node_id/weekly' => 'stats#chart', as: :weekly_stats
  get 'stats/:node_id/weekly_data' => 'stats#weekly_data', as: :weekly_data_stats
  # get 'stats/:node_id/daily' => 'stats#chart', as: :daily_stats
  get 'stats/:node_id/daily_data' => 'stats#daily_data', as: :daily_data_stats
  get 'stats/:node_id/daily_per_month_data' => 'stats#daily_per_month_data', as: :daily_per_month_data_stats
  get 'stats/:node_id/slot_percentage_data' => 'stats#slot_percentage_data', as: :slot_percentage_data_stats
  # get 'stats/:node_id/real_time' => 'stats#chart', as: :real_time_stats
  get 'stats/:node_id/real_time_data' => 'stats#real_time_data', as: :real_time_data_stats
  get 'stats/:node_id/:chart' => 'stats#chart', as: :chart_stats, constraints: { chart: /yearly|monthly|weekly|daily|real_time|time_series|daily_per_month/ }
  get 'stats/:node_id/time_interval' => 'stats#time_interval', as: :time_interval_stats

end

app/models/node.rb
class Node < ActiveRecord::Base
  belongs_to :user
  has_many :pulses, dependent: :delete_all
  has_many :stats, dependent: :destroy

  attr_accessor :clear_on_import, :import
	before_save :ensure_authentication_token, :init_token, :clean_dashboard
  validates :pulses_per_kwh, numericality: { only_integer: true, greater_than: 0 }
  validates :title, :pulses_per_kwh, :time_zone,  presence: true
  serialize :dashboard, Array
  after_initialize { dashboard = ['real_time', 'daily', 'weekly', 'monthly', 'yearly'] }

  def pulse_count
    self.pulses.count
  end

  def pulse_first
    q = self.pulses.order(:pulse_time).first
    q.pulse_time.in_time_zone unless q.nil?
  end

  def pulse_last
    q = self.pulses.order(:pulse_time).last
    q.pulse_time.in_time_zone unless q.nil?
  end

  def init_token
    authentication_token |= generate_authentication_token if new_record?
  end

  def ensure_authentication_token
    if authentication_token.blank?
      self.authentication_token = generate_authentication_token
    end
  end

  private
  
  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless Node.where(authentication_token: token).first
    end
  end

  def clean_dashboard
    dashboard.reject! { |c| c.empty? }
  end

end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController

	before_filter :authenticate_user!

	def index
		node_list
	end

	def new
		@node = Node.new(user: current_user)
		render 'edit'
	end

	def edit
		@node = Node.where(id: params[:id], user: current_user).first
		redirect_to(root_url) and return if @node.nil?
		@current_node = @node
		render 'edit'
	end

	def update
		@node = Node.where(id: params[:id], user: current_user).first
		if @node.update_attributes(node_params)
			rows_imported = import
			redirect_to nodes_url, notice: "Node '#{@node.title}' successfully updated" + (rows_imported.nil? ? "" : " and imported #{rows_imported} rows") + "."
		else
			render 'edit'
		end
	end

	def create
		@node = Node.new(node_params)
		@node.user = current_user
		if @node.save
			rows_imported = import
			redirect_to nodes_url, notice: "Node '#{@node.title}' successfully created" + (rows_imported.nil? ? "" : " and imported #{rows_imported} rows") + "."
			@nodes = nil
		else
			render 'edit'
		end
	end
	
	def destroy
		@node = Node.where(id: params[:id], user: current_user).first
		redirect_to(root_url) and return if @node.nil?
		@node.destroy
		flash[:success] = "Node deleted"
		redirect_to nodes_url
  end

	def show
		# @node = Node.where(id: params[:id], user: current_user).first
		# redirect_to root_url if @node.nil?
		# @current_node = @node
		edit
	end

	def import
		pn = Node.new(node_params)
		clear_on_input = ("1" == pn.clear_on_import ? true : false)
		rows_imported = Pulse.import(@node.id, pn.import.path, clear_on_input) unless pn.import.nil?
	end

	# def import
	# 	if params[:id].nil? || params[:file].nil?
	# 		redirect_to node_path, alert: "Import failed." 
	# 	else
	# 		Pulse.import(params[:id], params[:file].path)
	# 		redirect_to node_path, notice: "Import completed."
	# 	end
	# end

	def export
		id = params[:id]
		send_data Pulse.export(id), filename: "export_#{id}.csv"
	end

	private

	def node_params
		params.require(:node).permit(:title, :pulses_per_kwh, :time_zone, :clear_on_import, :import, dashboard: [])
	end

end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/edit.html.erb
<div class="page-header">
	<h2><%= @node.new_record? ? "New" : "Edit" %> Node</h2>
</div>

<% Time.zone = current_node.time_zone unless @current_node.nil? || @current_node.time_zone.nil? || @current_node.time_zone.empty? %>

<%= simple_form_for @node, multipart: true do |f| %>

<div class="panel panel-default">

	<div class="panel-heading">
		<h3 class="panel-title">Settings</h3>
	</div>

	<div class="panel-body">
		<%= f.input :title %>
		<%= f.input :pulses_per_kwh, as: :integer, label: "Pulses per kWh" %>
		<%= f.input :time_zone %>
		<%= f.input :dashboard, collection: ['real_time', 'daily', 'weekly', 'monthly', 'daily_per_month', 'yearly', 'time_series'].collect { |v| [ v.humanize, v ] }, as: :check_boxes %>
		<%= f.input :authentication_token, readonly: true %>
		<%= f.input :import, as: :file, input_html: { onchange: "validateFiles(this)", :data => { :max_file_size => 5.megabytes } } %>
		<%= f.input :clear_on_import, as: :boolean, label: "Remove all data before import WARNING: all existing data will be lost" unless @node.new_record? %>
	</div>

  <div class="panel-footer">
	  <%= f.button :submit, class: "btn btn-primary", data: { disable_with: 'Saving...'} %>
	  <%= link_to "Cancel", nodes_path, class: "btn btn-default" %>
  </div>

</div>

<% end %>

<% if !@node.new_record? %>

<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">emonLight RaspberryPi configuration</h3>
	</div>

	<div class="panel-body">
		<pre>remote = "emonlight"
url = "<%= "#{input_read_url}" %>"
api-key = "<%=@node.authentication_token%>"</pre>
	</div>

</div>

<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Data</h3>
	</div>

	<div class="panel-body">
			<strong>Pulse count</strong>
			<div class="well well-sm"><%= number_with_delimiter(@node.pulse_count) %></div>
			<strong>Starting at</strong>
			<div class="well well-sm"><%= (d = @node.pulse_first).nil? ? "" : time_tag(d.in_time_zone) %></div>
			<strong>Ending at</strong>
			<div class="well well-sm"><%= (d = @node.pulse_last).nil? ? "" : time_tag(d.in_time_zone) %></div>
	</div>

  <div class="panel-footer">
		<%= link_to(export_node_path(@node), method: :post, class: "btn btn-default") do %>
  				<span class="glyphicon glyphicon-export" aria-hidden="true"></span>
  				Export
  	<% end %>
  </div>

</div>

<% end %>

app/views/nodes/index.html.erb
<div class="page-header">
	<h2>Nodes</h2>
</div>

<div class="panel panel-default">

	<div class="panel-body">

	<table class="table table-bordered">
		<thead>
			<tr>
				<th>Node title</th>
				<th style="width: 10%">Pulse count</th>
				<th style="width: 20%">Last pulse</th>
				<th style="width: 20%">Time Zone</th>
				<th class="right">Actions</th>
			</tr>
		</thead>
		<tbody>
<% for n in @nodes %>
	<% Time.zone = n.time_zone unless n.nil? || n.time_zone.nil? || n.time_zone.empty? %>
		<tr>
			<td><%= link_to n.title, dashboard_stats_path(n) %></td>
			<td style="text-align:right; width: 10%"><%= number_with_delimiter(n.pulse_count) %></td>
			<td><%= (d = n.pulse_last).nil? ? "" : time_tag(d) %></td>
			<td><%= d.nil? ? "" : Time.zone.name %></td>
			<td class="right">
				<%= link_to dashboard_stats_path(n), class: "btn btn-sm" do %>
  				<span class="glyphicon glyphicon-dashboard" aria-hidden="true" aria-label="Dashboard"></span>
  			<% end %>
				<%= link_to(edit_node_path(n), class: "btn btn-sm") do %>
  				<span class="glyphicon glyphicon-edit" aria-hidden="true" aria-label="Edit"></span>
  			<% end %>
				<%= link_to(node_path(n), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm") do %>
  				<span class="glyphicon glyphicon-trash" aria-hidden="true" aria-label="Delete"></span>
  			<% end %>
  		</td>
  	</tr>  	
<% end %>
		</tbody>
		<tfoot>
			<tr>
				<th colspan="4"></th>
				<th><%= link_to(new_node_path, {class: "btn btn-sm"}) do %>
					<span class="glyphicon glyphicon-plus" aria-hidden="true" aria-label="Add node"></span>
					<% end %>
				</th>
			</tr>
		</tfoot>

	</table>

	</div>

</div>

app/views/nodes/new.html.erb
<div class="page-header">
	<h2><%= @node.new_record? ? "Create" : "Edit" %> Node</h2>
</div>

<div class="panel panel-default">


<%= simple_form_for @node do |f| %>
	<div class="panel-body">

  <%= f.input :title %>
  <%= f.input :time_zone %>

 </div>

  <div class="panel-footer">
  <%= f.button :submit %>
  <%= link_to "Cancel", :back, {class: "btn btn-default"} %>
  </div>
<% end %>

</div>

app/views/nodes/show.html.erb
<div class="page-header">
	<h2>Node content</h2>
</div>

<div class="panel panel-default">

	<div class="panel-heading">
		<h3 class="panel-title">Node content</h3>
	</div>

	<div class="panel-body">
	
		<p>Title: <%= @node.title %> </p>
		<p>Time zone: <%= @node.time_zone %> </p>
		<p>Token: <%= @node.authentication_token %> </p>
		<p>Pulse count: <%= @node.pulses.count %></p>
		<p>Starting from: <%= q = @node.pulses.order(:pulse_time).first; q.pulse_time unless q.nil? %></p>
		<p>Ending at: <%= q = @node.pulses.order(:pulse_time).last; q.pulse_time unless q.nil? %></p>

		<p>
		<%= form_tag import_node_path(@node), multipart: true do %>
			<%= file_field_tag :file %>
			<%= submit_tag "Import CSV" %>
		<% end %>
		</p>

	</div>

  <div class="panel-footer">
    <%= link_to "List", nodes_path, {class: "btn btn-default"} %>
    <%= link_to "New", new_node_path, {class: "btn btn-default"} %>
    <%= link_to "Edit", edit_node_path(@node), {class: "btn btn-default"} %>
    <%= link_to "Delete", node_path(@node), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
  </div>

</div>