config/routes.rb
Rails.application.routes.draw do

  get 'help/getting_started'
  get 'help/webapp_setup'

  authenticated :user do
    root :to => "nodes#index", as: :authenticated_root
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :nodes do
  	member do
  		post 'import'
      post 'export'
  	end
  end

  post 'input/read'

  get 'stats/:node_id/dashboard' => 'stats#dashboard', as: :dashboard_stats
  get 'stats/:node_id/time_series_data' => 'stats#time_series_data', as: :time_series_data_stats
  get 'stats/:node_id/yearly_data' => 'stats#yearly_data', as: :yearly_data_stats
  # get 'stats/:node_id/monthly' => 'stats#chart', as: :monthly_stats
  get 'stats/:node_id/monthly_data' => 'stats#monthly_data', as: :monthly_data_stats
  # get 'stats/:node_id/weekly' => 'stats#chart', as: :weekly_stats
  get 'stats/:node_id/weekly_data' => 'stats#weekly_data', as: :weekly_data_stats
  # get 'stats/:node_id/daily' => 'stats#chart', as: :daily_stats
  get 'stats/:node_id/daily_data' => 'stats#daily_data', as: :daily_data_stats
  get 'stats/:node_id/daily_per_month_data' => 'stats#daily_per_month_data', as: :daily_per_month_data_stats
  get 'stats/:node_id/slot_percentage_data' => 'stats#slot_percentage_data', as: :slot_percentage_data_stats
  # get 'stats/:node_id/real_time' => 'stats#chart', as: :real_time_stats
  get 'stats/:node_id/real_time_data' => 'stats#real_time_data', as: :real_time_data_stats
  get 'stats/:node_id/:chart' => 'stats#chart', as: :chart_stats, constraints: { chart: /yearly|monthly|weekly|daily|real_time|time_series|daily_per_month/ }
  get 'stats/:node_id/time_interval' => 'stats#time_interval', as: :time_interval_stats

end

app/models/stat.rb
class Stat < ActiveRecord::Base
  belongs_to :node
  has_many :stat_values, dependent: :delete_all
  include MeanCalculator

  # def self.current_stat_mean(current_node, stat, period, where_clause = nil)
  #   Stat.find_or_initialize_by(node: current_node, stat: stat, period: period, where_clause: where_clause)
  # end

end

app/controllers/stats_controller.rb
class StatsController < ApplicationController

  before_action :authenticate_user!, :verify_current_node

  def dashboard
  	@charts = current_node.dashboard
  	render "chart"
  end

  def chart
  	@charts = [params[:chart]]
  end

	def real_time_data
		time = params[:time] ? Time.zone.parse(params[:time]) : Time.zone.now - 5
		q = Rails.cache.fetch("#{current_node.cache_key}/real_time_data/#{time}", expires_in: 4.seconds) do
			data = Pulse.where("node_id = :node and pulse_time > :time", { node: params[:node_id], time: time }).order(:pulse_time).pluck(:pulse_time, :power)
		end
		render json: q
	end

	def yearly_data
		opts = { force: params[:force] == "true", expires_in: 10.minutes }
		q = DataService.cached_calc(:yearly_data, current_node, params, opts)
  	render json: q
	end

	def monthly_data
		opts = { force: params[:force] == "true", expires_in: 10.minutes }
		q = DataService.cached_calc(:monthly_data, current_node, params, opts)
  	render json: q
	end

	def weekly_data
		opts = { force: params[:force] == "true", expires_in: 10.minutes }
		q = DataService.cached_calc(:weekly_data, current_node, params, opts)
  	render json: q
	end

	def daily_data
		opts = { force: params[:force] == "true", expires_in: 5.minutes }
		q = DataService.cached_calc(:daily_data, current_node, params, opts)
  	render json: q
	end

	def time_series_data
		opts = { force: params[:force] == "true", expires_in: 5.minutes }
		q = DataService.cached_time_series_data(current_node, params, opts)
  	render plain: q
	end

	def daily_per_month_data
		opts = { force: params[:force] == "true", expires_in: 10.minutes }
		q = DataService.cached_calc(:daily_per_month_data, current_node, params, opts)
  	render json: q
	end

	def slot_percentage_data
		opts = { force: params[:force] == "true", expires_in: 10.minutes }
		q = DataService.cached_calc(:slot_percentage_data, current_node, params, opts)
  	render json: q
	end

	def time_interval
		p = current_node.pulses.order(:pulse_time).first
		t0 = p.pulse_time if p
		p = current_node.pulses.order(:pulse_time).last
		t1 = p.pulse_time if p
		render json: { time_start: t0, time_end: t1 }
	end

end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/stats/_chart.html.erb
<% case chart
	when "real_time" %>

<div class="chart" id="chart_real_time_div"></div>
<div id="chart_real_time_control" class=" btn-group hidden">
	<!-- <div class="btn-group"> -->
		<button id="real_time_btn" type="button" class="btn btn-default btn-sm">Default</button>
	  <button id="real_time_dropdown" type="button" class="btn btn-default dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	    <span class="caret"></span>
	    <span class="sr-only">Toggle Dropdown</span>
	  </button>
	  <ul id="real_time_actions" data-default="3" class="dropdown-menu">
	    <li><a href="#">5</a></li>
	    <li><a href="#">10</a></li>
	    <li><a href="#">30</a></li>
	    <li><a href="#">60</a></li>
	    <li><a href="#">120</a></li>
	    <li><a href="#">240</a></li>
	    <li><a href="#">480</a></li>
	    <li><a href="#">1440</a></li>
	  </ul>
	<!-- </div> -->
</div>

<% when "yearly" %>

<div class="chart" id="chart_yearly_div"></div>

<% when "monthly" %>

<div class="chart" id="chart_monthly_div"></div>

<% when "weekly" %>

<div class="chart" id="chart_weekly_div"></div>

<% when "daily" %>

<div class="chart" id="chart_daily_div"></div>

<% when "time_series" %>

<div id="chart_time_series_div"></div>
<div id="slider_div"></div>

<% when "daily_per_month" %>

<div class="chart" id="chart_daily_per_month_div"></div>

<div class="chart" id="chart_slot_percentage_div"></div>

<% end %>

app/views/stats/_onload.html.erb
<% offset = Time.zone.now.utc_offset %>
<script type="text/javascript">
  if ($("#chart_real_time_div").length) {
    $("#real_time_actions").delegate("a", "click", function(i) {
      var t = $(this).text();
      // console.log(t);
      $("#real_time_btn").text("Time interval " + t + " min"); 
      drawRealTimeChart("<%=real_time_data_stats_path(current_node)%>", 'chart_real_time_div', t, <%= offset %>);
    });
    var i = $("#real_time_actions").data("default");
    $("#real_time_actions a")[i].click();
  }
  else if (window.realTimeIntervalId)
    clearInterval(window.realTimeIntervalId);
  if ($("#chart_weekly_div").length)
    drawWeeklyChart("<%=weekly_data_stats_path(current_node)%>", 'chart_weekly_div', <%= offset %>);
  if ($("#chart_daily_div").length)
    drawDailyChart("<%=daily_data_stats_path(current_node)%>", 'chart_daily_div', <%= offset %>);
  if ($("#chart_monthly_div").length)
    drawMonthlyChart("<%=monthly_data_stats_path(current_node)%>", 'chart_monthly_div', <%= offset %>);
  if ($("#chart_yearly_div").length)
    drawYearlyChart("<%=yearly_data_stats_path(current_node)%>", 'chart_yearly_div', <%= offset %>);
  if ($("#chart_time_series_div").length)
      TS.init("chart_time_series_div", "slider_div", "<%=time_series_data_stats_path(current_node, format: :json)%>", "<%=time_interval_stats_path(current_node, format: :json)%>", <%= offset %>);
  if ($("#chart_daily_per_month_div").length) {
    drawDailyPerMonthChart("<%=daily_per_month_data_stats_path(current_node)%>", 'chart_daily_per_month_div', <%= offset %>);
    drawSlotPercentageChart("<%=slot_percentage_data_stats_path(current_node)%>", 'chart_slot_percentage_div', <%= offset %>);
  }
</script>

app/views/stats/chart.html.erb
<!-- 7 -->

<div class="panel panel-default">

  <div class="panel-heading clearfix">
    <h3 class="panel-title pull-left">
    	<%=current_node.title %> &nbsp; <small>Time zone <b><%= current_node.time_zone %></b></small>
    </h3>
    <h3 class="panel-title pull-right">
      <%= link_to url_for, class: "btn btn-default btn-xs", onclick: "window.forceRefresh = true" do %>
        <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
        Refresh
      <% end %>
   	  <%= link_to edit_node_path(current_node), class: "btn btn-default btn-xs" do %>
   	  	<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
   	  	Edit
   	  <% end %>
    </h3>
  </div>

  <div class="panel-body">
		<% @charts.each.with_index do |c, i| %>
			<%= render partial: 'chart', locals: { chart: c } %>
      <% if i < @charts.length - 1 %><hr><% end %>
		<% end %>
  </div>

</div>

<%= render partial: "onload", locals: { force: params[:force] } %>

<% offset = Time.zone.now.utc_offset %>

app/views/stats/dashboard.html.erb
<div class="panel panel-default">

  <div class="panel-heading clearfix">
    <h3 class="panel-title pull-left">
    	<%=current_node.title %> &nbsp; <small>Time zone <b><%= current_node.time_zone %></b></small>
    </h3>
    <h3 class="panel-title pull-right">
      <%= link_to url_for, class: "btn btn-default btn-xs", onclick: "window.forceRefresh = true" do %>
        <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
        Refresh
      <% end %>
   	  <%= link_to edit_node_path(current_node), class: "btn btn-default btn-xs" do %>
   	  	<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
   	  	Edit
   	  <% end %>
    </h3>
  </div>

  <div class="panel-body">
		<% for c in @charts %>
			<%= render partial: 'chart', locals: { chart: c } %>
		<% end %>
  </div>

</div>

<%= render partial: "onload" %>