config/routes.rb
Rails.application.routes.draw do

  get 'help/getting_started'
  get 'help/webapp_setup'

  authenticated :user do
    root :to => "nodes#index", as: :authenticated_root
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :nodes do
  	member do
  		post 'import'
      post 'export'
  	end
  end

  post 'input/read'

  get 'stats/:node_id/dashboard' => 'stats#dashboard', as: :dashboard_stats
  get 'stats/:node_id/time_series_data' => 'stats#time_series_data', as: :time_series_data_stats
  get 'stats/:node_id/yearly_data' => 'stats#yearly_data', as: :yearly_data_stats
  # get 'stats/:node_id/monthly' => 'stats#chart', as: :monthly_stats
  get 'stats/:node_id/monthly_data' => 'stats#monthly_data', as: :monthly_data_stats
  # get 'stats/:node_id/weekly' => 'stats#chart', as: :weekly_stats
  get 'stats/:node_id/weekly_data' => 'stats#weekly_data', as: :weekly_data_stats
  # get 'stats/:node_id/daily' => 'stats#chart', as: :daily_stats
  get 'stats/:node_id/daily_data' => 'stats#daily_data', as: :daily_data_stats
  get 'stats/:node_id/daily_per_month_data' => 'stats#daily_per_month_data', as: :daily_per_month_data_stats
  get 'stats/:node_id/slot_percentage_data' => 'stats#slot_percentage_data', as: :slot_percentage_data_stats
  # get 'stats/:node_id/real_time' => 'stats#chart', as: :real_time_stats
  get 'stats/:node_id/real_time_data' => 'stats#real_time_data', as: :real_time_data_stats
  get 'stats/:node_id/:chart' => 'stats#chart', as: :chart_stats, constraints: { chart: /yearly|monthly|weekly|daily|real_time|time_series|daily_per_month/ }
  get 'stats/:node_id/time_interval' => 'stats#time_interval', as: :time_interval_stats

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <%= render 'layouts/navigation_links' %>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<ul class="nav navbar-nav">
<% if user_signed_in? %>
	<li class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Manage Nodes<span class="caret"></span></a>
		<ul class="dropdown-menu">
			<li><%= link_to 'Nodes', nodes_path %></li>
			<li><%= link_to 'New node', new_node_path %></li>
<% for node in node_list %>
			<li><%= link_to node.title, dashboard_stats_path(node) %></li>
<% end %>
		</ul>
	</li>
<% if current_node %>
	<li class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Stats for <%= current_node.title %><span class="caret"></span></a>
		<ul class="dropdown-menu">
			<li><%= link_to 'Dashboard', dashboard_stats_path(current_node) %></li>
			<li><%= link_to 'Real time', chart_stats_path(current_node, :real_time) %></li>
			<li><%= link_to 'Daily', chart_stats_path(current_node, :daily) %></li>
			<li><%= link_to 'Weekly', chart_stats_path(current_node, :weekly) %></li>
			<li><%= link_to 'Monthly', chart_stats_path(current_node, :monthly) %></li>
			<li><%= link_to 'Daily per Month', chart_stats_path(current_node, :daily_per_month) %></li>
			<li><%= link_to 'Yearly', chart_stats_path(current_node, :yearly) %></li>
			<li><%= link_to 'Time Series', chart_stats_path(current_node, :time_series) %></li>
		</ul>
	</li>
<% end #if current_node %>
<% end #if user_signed %>
</ul>
<ul class="nav navbar-nav navbar-right">

  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Help<span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><%= link_to 'Getting started', help_getting_started_path %></li>
      <li><%= link_to 'Setup web app', help_webapp_setup_path %></li>
    </ul>
  </li>

<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : 'Emonlight' %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Emonlight" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag '//www.google.com/jsapi' %>
    <%#= javascript_include_tag 'jquery.mousewheel.min', 'data-turbolinks-track' => true %>
    <%#= javascript_include_tag 'jQDateRangeSlider-withRuler-min', 'data-turbolinks-track' => true %>
    <%#= stylesheet_link_tag 'iThing', media: 'all', 'data-turbolinks-track' => true %>
    <script type="text/javascript">
      google.load('visualization', '1.0', {'packages':['corechart', 'controls']});
    </script>

    <%= yield :head %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <% if controller_name == 'help' %>
        <div class="page-header">
          <h2><%= action_name.humanize %></h2>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <%= yield %>
          </div>
        </div>
      <% else %>
          <%= yield %>
      <% end %>
    </main>
  </body>
</html>

app/views/layouts/stats.html.erb
<% content_for :head do %>
  <script type="text/javascript">
  	// Load the Visualization API and the piechart package.
		//google.load('visualization', '1.0', {'packages':['corechart']});

	</script>
<% end %>
<%= render template: "layouts/application" %>

app/views/layouts/visitors.html.erb
<% content_for :head do %>
    <%= stylesheet_link_tag 'carousel', media: 'all', 'data-turbolinks-track' => true %>
<% end %>
<%= render template: "layouts/application" %>